### PR TITLE
added travis ci build bot

### PR DESCRIPTION
**Pull request by aadityabagga**
related issue: https://github.com/cromnix/artix/issues/1

### CODE REVIEW

**Comment by aadityabagga** [comment]
@udeved yup, have borrowed a few functions from there.

The name manjaro-bootstrap is used because it uses git repo of the same name; feel free to modify it or use basestrap directly as you mentioned :-)

**Comment by udeved** [comment]
I am bit confused, as far as I see, this won't work with artix, we have the same package names as arch?

Could you send new pr to a travisci branch where we can experiment before merging to master?

**Comment by aadityabagga** [comment]
@udeved it uses arch/manjaro environment as bootstrap for running buildpkg; can the current artix packages hosted somewhere be used along with artools for bootstrap env?

**Comment by udeved** [comment]
Yep @aadityabagga 

https://sourceforge.net/projects/cromnix/files/fork/

Fully system repo, some binary packages from arch, but all fine.
I run it already on two systems, chris converted his arch too afaik.
Mirrors work too.

**Comment by udeved** [comment]
https://github.com/cromnix/artix/commit/e3411bfd8268b53777db5d17424f55d23e11e99d

current mirrors ;)

**Comment by aadityabagga** [comment]
That's cool!

In that case the buildbot code would need to be updated to use the new repos and

**Comment by udeved** [comment]
Should be similar how the arch travis sets up chroot in terms of base-devel. ;)
Simplifies things to have a dedicated no systemd core repo.

**Pull request closed without merging**
